filters:
  city: detroit
  agentType: privatePerson
  areaTotal_min: 10
  district:
    - район 1
    - район 2
    - район 3
  flatType: [1, 2, 3, 4, 6, gostinka]
  floor_min: 2
  price_min: 1
  price_max: 99999
  rentPeriod: 12
scrape_interval: 30
